fixed low battery crash
Hi, 
We got another exception after getting "low battery" message.





<<< imei:863070011991451,tracker,1304111338,,F,053814.000,A,3206.0971,N,03448.52

52,E,7.87,333.72,;

<<< imei:863070011991451,low battery,1304111338,,F,053817.000,A,3206.1056,N,0344

8.5179,E,10.40,357.17,;

Traceback (most recent call last):

  File "manage.py", line 10, in <module>

    execute_from_command_line(sys.argv)

  File "C:\Python27\lib\site-packages\django\core\management\__init__.py", line

443, in execute_from_command_line

    utility.execute()

  File "C:\Python27\lib\site-packages\django\core\management\__init__.py", line

382, in execute

    self.fetch_command(subcommand).run_from_argv(self.argv)

  File "C:\Python27\lib\site-packages\django\core\management\base.py", line 196,

 in run_from_argv

    self.execute(*args, **options.__dict__)

  File "C:\Python27\lib\site-packages\django\core\management\base.py", line 232,

 in execute

    output = self.handle(*args, **options)

  File "D:\GitHub\octoninja\website\gpsweb\management\commands\start_gps_server.

py", line 18, in handle

    serv.start()

  File "D:\GitHub\octoninja\website\gpsweb\management\commands\gps_server\Server

.py", line 138, in start

    self.recvFromClientSocket(s)

  File "D:\GitHub\octoninja\website\gpsweb\management\commands\gps_server\Server

.py", line 95, in recvFromClientSocket

    self.queue_message(clientSocket, "**,IMEIs:%clientSocket,E" % self.IMEIs[cli

entSocket])

TypeError: %c requires int or char




D:\GitHub\octoninja\website>pause

Press any key to continue . . .